### ISSUE TITLE
Error at epoch 1

### ISSUE THREAD

**Issue by coralexbadea** [Sindhu-Hegde/you_said_that#3]
None
Epoch 1/20
Traceback (most recent call last):
  File "train.py", line 159, in <module>
    int(args.no_of_still_images), args.model_directory)
  File "train.py", line 116, in model
    callbacks=[tensorboard_callback, early_stopping, checkpoint]
  File "/usr/local/lib/python3.6/dist-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1508, in train_on_batch
    class_weight=class_weight)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 579, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_utils.py", line 135, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input_1 to have 4 dimensions, but got array with shape (0, 1)

**Comment by Sindhu-Hegde** [comment]
Check the path of the pre-processed data, the shape of the audio (input_1) should be (Bx12x35x1). In your case, the audio files are not being loaded.

**Comment by roopeshn28** [comment]
@coralexbadea can you please tell me how you were able to resolve?

**Comment by coralexbadea** [comment]
Sorry, I was in a hurry then and I had to use https://github.com/Rudrabha/Wav2Lip.git . But looking back the solution given by @Sindhu-Hegde is the answer.

**Comment by Tafreenzhussain** [comment]
> 

ValueError: Input 0 is incompatible with layer conv2d_1: expected ndim=4, found ndim=5

After changing the shape of input_1, we have got this error ( B we have used as batch_size)

**Comment by hamzakhalil798** [comment]
@coralexbadea have you tried to fix it?
@roopeshn28 
@Sindhu-Hegde 
I'm running into same error... path is also file.
-f='features/'
iv used the sample data provided for extracting features
